import './_esnmain.js';
import {jsonldDOTcompact} from './jsonldDOTcompact';
export const compact = jsonldDOTcompact;
import {jsonldDOTexpand} from './jsonldDOTexpand';
export const expand = jsonldDOTexpand;
import {jsonldDOTflatten} from './jsonldDOTflatten';
export const flatten = jsonldDOTflatten;
import {jsonldDOTframe} from './jsonldDOTframe';
export const frame = jsonldDOTframe;
import {jsonldDOTlink} from './jsonldDOTlink';
export const link = jsonldDOTlink;
import {jsonldDOTnormalize} from './jsonldDOTnormalize';
export const normalize = jsonldDOTnormalize;
import {jsonldDOTfromRDF} from './jsonldDOTfromRDF';
export const fromRDF = jsonldDOTfromRDF;
import {jsonldDOTtoRDF} from './jsonldDOTtoRDF';
export const toRDF = jsonldDOTtoRDF;
import {jsonldDOTcreateNodeMap} from './jsonldDOTcreateNodeMap';
export const createNodeMap = jsonldDOTcreateNodeMap;
import {jsonldDOTmerge} from './jsonldDOTmerge';
export const merge = jsonldDOTmerge;
import {jsonldDOTrelabelBlankNodes} from './jsonldDOTrelabelBlankNodes';
export const relabelBlankNodes = jsonldDOTrelabelBlankNodes;
import {jsonldDOTprependBase} from './jsonldDOTprependBase';
export const prependBase = jsonldDOTprependBase;
import {jsonldDOTpromises} from './jsonldDOTpromises';
export const promises = jsonldDOTpromises;
import {jsonldDOTpromisify} from './jsonldDOTpromisify';
export const promisify = jsonldDOTpromisify;
import {jsonldDOTJsonLdProcessor} from './jsonldDOTJsonLdProcessor';
export const JsonLdProcessor = jsonldDOTJsonLdProcessor;
import {jsonldDOTparseLinkHeader} from './jsonldDOTparseLinkHeader';
export const parseLinkHeader = jsonldDOTparseLinkHeader;
import {jsonldDOTRequestQueue} from './jsonldDOTRequestQueue';
export const RequestQueue = jsonldDOTRequestQueue;
import {jsonldDOTActiveContextCache} from './jsonldDOTActiveContextCache';
export const ActiveContextCache = jsonldDOTActiveContextCache;
import {jsonldDOTcache} from './jsonldDOTcache';
export const cache = jsonldDOTcache;
import {jsonldDOTprocessContext} from './jsonldDOTprocessContext';
export const processContext = jsonldDOTprocessContext;
import {jsonldDOThasProperty} from './jsonldDOThasProperty';
export const hasProperty = jsonldDOThasProperty;
import {jsonldDOThasValue} from './jsonldDOThasValue';
export const hasValue = jsonldDOThasValue;
import {jsonldDOTaddValue} from './jsonldDOTaddValue';
export const addValue = jsonldDOTaddValue;
import {jsonldDOTgetValues} from './jsonldDOTgetValues';
export const getValues = jsonldDOTgetValues;
import {jsonldDOTremoveProperty} from './jsonldDOTremoveProperty';
export const removeProperty = jsonldDOTremoveProperty;
import {jsonldDOTremoveValue} from './jsonldDOTremoveValue';
export const removeValue = jsonldDOTremoveValue;
import {jsonldDOTcompareValues} from './jsonldDOTcompareValues';
export const compareValues = jsonldDOTcompareValues;
import {jsonldDOTgetContextValue} from './jsonldDOTgetContextValue';
export const getContextValue = jsonldDOTgetContextValue;
import {jsonldDOTregisterRDFParser} from './jsonldDOTregisterRDFParser';
export const registerRDFParser = jsonldDOTregisterRDFParser;
import {jsonldDOTunregisterRDFParser} from './jsonldDOTunregisterRDFParser';
export const unregisterRDFParser = jsonldDOTunregisterRDFParser;
import {jsonldDOTIdentifierIssuer} from './jsonldDOTIdentifierIssuer';
export const IdentifierIssuer = jsonldDOTIdentifierIssuer;
import {jsonldDOTUniqueNamer} from './jsonldDOTUniqueNamer';
export const UniqueNamer = jsonldDOTUniqueNamer;
import {jsonldDOTurl} from './jsonldDOTurl';
export const url = jsonldDOTurl;